# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/VIVADO/PROY2/lab02-g03/Ejercicios/Proyectos/Ejercicio5/src/constraints/program_counter.xdc

# IP: D:/VIVADO/PROY2/lab02-g03/Ejercicios/Compartido/xci/WCLK/WCLK.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WCLK || ORIG_REF_NAME==WCLK} -quiet] -quiet
