# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Constraints/constraints_memoria_4x8.xdc

# IP: ip/WCLK/WCLK.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WCLK || ORIG_REF_NAME==WCLK} -quiet] -quiet
