# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Laboratorio_2/Respaldo/Ejercicios_29_08_2022/Constraints/constraints_contador_7seg.xdc

# IP: C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Laboratorio_2/Respaldo/Ejercicios_29_08_2022/Compartido/xci/WCLK/WCLK.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WCLK || ORIG_REF_NAME==WCLK} -quiet] -quiet
