# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/TDD/lab02-g03/Ejercicios/Constraints/constraints_contador_7seg.xdc

# IP: C:/TDD/lab02-g03/Ejercicios/Compartido/xci/WCLK/WCLK.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==WCLK || ORIG_REF_NAME==WCLK} -quiet] -quiet
