# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config -id {Common 17-41} -limit 10000000

start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param chipscope.maxJobs 1
  create_project -in_memory -part xc7a100tcsg324-1
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
<<<<<<<< HEAD:Ejercicios/Proyectos/Ejercicio4/vivido_project.runs/impl_1/top_simulate_7seg_v2.tcl
  set_property webtalk.parent_dir C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Laboratorio_2/Repositorio/lab02-g03/Ejercicios/Proyectos/Ejercicio4/vivido_project.cache/wt [current_project]
  set_property parent.project_path C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Laboratorio_2/Repositorio/lab02-g03/Ejercicios/Proyectos/Ejercicio4/vivido_project.xpr [current_project]
  set_property ip_output_repo C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Laboratorio_2/Repositorio/lab02-g03/Ejercicios/Proyectos/Ejercicio4/vivido_project.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES XPM_CDC [current_project]
  add_files -quiet C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Laboratorio_2/Repositorio/lab02-g03/Ejercicios/Proyectos/Ejercicio4/vivido_project.runs/synth_1/top_simulate_7seg_v2.dcp
  read_ip -quiet C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Laboratorio_2/Repositorio/lab02-g03/Ejercicios/Compartido/xci/WCLK/WCLK.xci
  read_xdc C:/Users/carlo/Andrey/TEC/Semestre_II_2022/Taller_Digitales/Laboratorios/Laboratorio_2/Repositorio/lab02-g03/Ejercicios/Constraints/contraints_7seg_v2.xdc
  link_design -top top_simulate_7seg_v2 -part xc7a100tcsg324-1
========
  set_property webtalk.parent_dir C:/TDD/lab02-g03/Ejercicios/Proyectos/Ejercicio1/vivado_project.cache/wt [current_project]
  set_property parent.project_path C:/TDD/lab02-g03/Ejercicios/Proyectos/Ejercicio1/vivado_project.xpr [current_project]
  set_property ip_output_repo C:/TDD/lab02-g03/Ejercicios/Proyectos/Ejercicio1/vivado_project.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES XPM_CDC [current_project]
  add_files -quiet C:/TDD/lab02-g03/Ejercicios/Proyectos/Ejercicio1/vivado_project.runs/synth_1/top_simulate.dcp
  read_ip -quiet C:/TDD/lab02-g03/Ejercicios/Compartido/xci/WCLK/WCLK.xci
  read_xdc C:/TDD/lab02-g03/Ejercicios/Constraints/constraints_contador_7seg.xdc
  link_design -top top_simulate -part xc7a100tcsg324-1
>>>>>>>> e82be317274dbddd999bc3e35a1cf024f72b017e:Ejercicios/Proyectos/Ejercicio4/vivido_project.runs/impl_1/top_simulate.tcl
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
<<<<<<<< HEAD:Ejercicios/Proyectos/Ejercicio4/vivido_project.runs/impl_1/top_simulate_7seg_v2.tcl
  write_checkpoint -force top_simulate_7seg_v2_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file top_simulate_7seg_v2_drc_opted.rpt -pb top_simulate_7seg_v2_drc_opted.pb -rpx top_simulate_7seg_v2_drc_opted.rpx"
========
  write_checkpoint -force top_simulate_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file top_simulate_drc_opted.rpt -pb top_simulate_drc_opted.pb -rpx top_simulate_drc_opted.rpx"
>>>>>>>> e82be317274dbddd999bc3e35a1cf024f72b017e:Ejercicios/Proyectos/Ejercicio4/vivido_project.runs/impl_1/top_simulate.tcl
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design 
<<<<<<<< HEAD:Ejercicios/Proyectos/Ejercicio4/vivido_project.runs/impl_1/top_simulate_7seg_v2.tcl
  write_checkpoint -force top_simulate_7seg_v2_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file top_simulate_7seg_v2_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file top_simulate_7seg_v2_utilization_placed.rpt -pb top_simulate_7seg_v2_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file top_simulate_7seg_v2_control_sets_placed.rpt"
========
  write_checkpoint -force top_simulate_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file top_simulate_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file top_simulate_utilization_placed.rpt -pb top_simulate_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file top_simulate_control_sets_placed.rpt"
>>>>>>>> e82be317274dbddd999bc3e35a1cf024f72b017e:Ejercicios/Proyectos/Ejercicio4/vivido_project.runs/impl_1/top_simulate.tcl
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
<<<<<<<< HEAD:Ejercicios/Proyectos/Ejercicio4/vivido_project.runs/impl_1/top_simulate_7seg_v2.tcl
  write_checkpoint -force top_simulate_7seg_v2_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file top_simulate_7seg_v2_drc_routed.rpt -pb top_simulate_7seg_v2_drc_routed.pb -rpx top_simulate_7seg_v2_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file top_simulate_7seg_v2_methodology_drc_routed.rpt -pb top_simulate_7seg_v2_methodology_drc_routed.pb -rpx top_simulate_7seg_v2_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file top_simulate_7seg_v2_power_routed.rpt -pb top_simulate_7seg_v2_power_summary_routed.pb -rpx top_simulate_7seg_v2_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file top_simulate_7seg_v2_route_status.rpt -pb top_simulate_7seg_v2_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file top_simulate_7seg_v2_timing_summary_routed.rpt -pb top_simulate_7seg_v2_timing_summary_routed.pb -rpx top_simulate_7seg_v2_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file top_simulate_7seg_v2_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file top_simulate_7seg_v2_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file top_simulate_7seg_v2_bus_skew_routed.rpt -pb top_simulate_7seg_v2_bus_skew_routed.pb -rpx top_simulate_7seg_v2_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force top_simulate_7seg_v2_routed_error.dcp
========
  write_checkpoint -force top_simulate_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file top_simulate_drc_routed.rpt -pb top_simulate_drc_routed.pb -rpx top_simulate_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file top_simulate_methodology_drc_routed.rpt -pb top_simulate_methodology_drc_routed.pb -rpx top_simulate_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file top_simulate_power_routed.rpt -pb top_simulate_power_summary_routed.pb -rpx top_simulate_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file top_simulate_route_status.rpt -pb top_simulate_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file top_simulate_timing_summary_routed.rpt -pb top_simulate_timing_summary_routed.pb -rpx top_simulate_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file top_simulate_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file top_simulate_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file top_simulate_bus_skew_routed.rpt -pb top_simulate_bus_skew_routed.pb -rpx top_simulate_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force top_simulate_routed_error.dcp
>>>>>>>> e82be317274dbddd999bc3e35a1cf024f72b017e:Ejercicios/Proyectos/Ejercicio4/vivido_project.runs/impl_1/top_simulate.tcl
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

