@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Aug 22 21:46:58 -0600 2022
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_module_7seg_v2_time_synth -key {Post-Synthesis:sim_1:Timing:tb_module_7seg_v2} -tclbatch tb_module_7seg_v2.tcl -log simulate.log"
call xsim  tb_module_7seg_v2_time_synth -key {Post-Synthesis:sim_1:Timing:tb_module_7seg_v2} -tclbatch tb_module_7seg_v2.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
